name: Checkov

on: pull_request

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: bridgecrewio/checkov-action@master
          with:
            quiet: true # optional: display only failed checks
